var labels = {
    loginUser: "EMILY'S",
    workspace: "Workspace",
    workQueue: "Task",
    work_Queue: "Work Queue",
    request: "Request",
    search: "Search",
    welcome: "Welcome",
    Search: "Search",
    and_symbol: "&",
    catalogRequest: "Catalog Request",
    requisition: "Requisition",
    bookmarks: "Bookmarks",
    eventCalendar: "Event Calendar",
    fileRepositories: "File Repositories",
    procurement: "Procurement",
    policies: "Policies",
    connect: "Connect",
    chat: "Chat",
    email: "Email",
    discussionForum: "Discussion Forum",
    reachUs: "Reach Us",
    sourcing: "Sourcing",
    home: "Home",
    spend: "Spend",
    dashboard: "Dashboard",
    reports: "Reports",
    opportunityFinder:"Opportunity Finder",
    dataExport: "Data Export",
    feedback: "Feedback",
    rfx: "RFx",
    auctions: "Auctions",
    auction: "Auction",
    contracts: "Contracts",
    forms: "Forms",
    scorecards: "Scorecards",
    actionPlan:"Action Plan",
    catalogs: "Catalogs",
	catalog: "Catalog",
    requisitions: "Requisitions",
    requisition: "Requisition",
    orders: "Orders",
    receipts: "Receipts",
    receipt: "Receipt",
    invoices: "Invoices",
    invoiceReconciliation: "Invoice Reconciliation",
    returnNote: "Return Note",
    creditMemo: "Credit Memo",
    programs: "Programs",
    partners: "Partners",
    kpi: "KPI",
    compliance: "Compliance",
    contract: "Contract",
    payment: "Payment",
    createRequesition: "Create Requesition",
    paymentRequest: "Payment Request",
    nonCatalogRequest: "Non-Catalog Request",
    accountDetails: "Account Details",
    drafts: "Drafts",
    draft: "Draft",
    showAll: "Show All",
    sendForApproval: "Send For Approval",
    advanced: "Advanced",
    done: "Done",
    usetemplate: "use template",
    pendingApprovals: "Pending Approvals",
    approved: "Approved",
    approvalRequired: "Approval Required",
    active: "Active",
    rejected: "Rejected",
    inProgress: "In Progress",
    responseInProgress: "Response In Progress",
    scoringInProgress: "Scoring In Progress",
    additionalInformation: "Additional Information",
    phoneNumber: "Phone Number",
    dfaultCurrency: "Default Currency",
    shippingLocation: "Shipping Location",
    timeZone: "Time Zone",
    langauge: "Langauge",
    electronicSignature: "Electronic Signature",
    enter: "Enter",
    name: "Name",
    select: "Select",
    category: "Category",
    businessUnit: "Business Unit",
    sourcingBuyer: "Sourcing Buyer",
    requestApprover: "Request Approver",
    legalEntity: "Legal Entity",
    OnBehalfOf: "On behalf of",
    event: "Event",
    description: "Description",
    anticipatedProjectCost: "Anticipated Project Cost",
    currency: "Currency",
    purchaseType: "Purchase Type",
    dateNeededBy: "Date Needed By",
    requestor: "Requestor",
    department: "Department",
    date: "Date",
    annual: "Annual",
    preview: "Preview",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    view: "View",
    apply: "Apply",
    workflow: "Workflow",
    accountDetails: "Account Details",
    by: "by",
    type: "Type",
    status: "Status",
    all: "All",
    urgent: "Urgent",
    filters: "Filters",
    filter: "Filter",
    overdue: "Overdue",
    to: "To",
    subject: "Subject",
    send: "Send",
    mail: "Mail",
    undo: "Undo",
    confirmReceipt: "Confirm Receipt",
	createRequest:"Create Request",
	createRequisition:"Create Requisition",
	sourcingBuyer:"Sourcing Buyer",
	reset:"Reset",
	newRequisition:"New Requisition",
	nonCatalogItem: "Non-Catalog Items",
	catalogItem: "Catalog Items",
	contact:"Contact",
	approvalPendingWith: "Approval Pending With",
	approver: "Approver",
	contracted:"Contracted",
	itTelecom:"IT Telecom",
	usd:"USD",
	per:"Per",
	item:"Item",
	add:"Add",
	toCart:"To Cart",
	qty:"QTY",
	uom:"Unit",
	what:"What",
	are:"are",
	you:"you",
	looking:"looking",
	for: "for",
	suppliers: "Suppliers",
	internal: "Internal",
	hosted: "Hosted",
	price: "Price",
    range:"Range",
	shipTo:"Ship To",
	as:"AS",
	number:"Number",
	recent:"Recent",
	remove:"Remove",
	punchout:"Punchout",
	suppliers:"Suppliers",
	partner: "Partner",
	quantity: "Quantity",
	bands: "Bands",
	manufacturer: "Manufacturer",
	partNo: "Part No",
	buyer: "Buyer",
	no: "No",
	number: "Number",
	tax: "Tax",
	exempt: "Exempt",
	reviews: "Reviews",
	more: "More",
	yes: "Yes",
	recently: "Recently",
	viewed:"Viewed",
	items:"Items",
	close:"Close",
	requestor:"Requestor's",
	partner: "Partner",
	costCenter:"Cost Center",
	projectCode:"Project Code",
	glCode:"GL Code",
	splitItemBy:"Split Item By",
	numberOfsplits:"Number Of Splits",
	manufacturer:"Manufacturer ",
	part:"Part",
	shippingMethod: "Shipping Method",
	address:"Address",
	deliver: "Deliver",
	expiry: "Expiry",
	value: "Value",
	terms: "Terms", 
	option: "Option",
	inventory: "Inventory",
	shipping: "Shipping",
	freight: "Freight",
	other: "Other",
	charges:"Charges",
	review: "Review",
	ok:"Ok",
	title:"Title",
	rating:"Rating",
	your:"Your",
	comment:"Comment",
	here:"Here",   
	shoping: "Shopping",
	cart: "Cart",
	view: "View",
	cart: "Cart",
	checkout: "Checkout",
	error:"ERROR",
	success:"Success",
	information:"Information",
	warning:"Warning",
	share:"Share",
	days:"Days",
	with:"With",
	template:"Template",   
    createblankRequesition: "create a blank requesition",
	set:"Set",
	default:"default",
	gep:"GEP",
	profile:"Profile",
	bookmark: "Bookmark",   
	notification:"Notification",
	navigation:"Navigation",
	back:"Back",
	clear:"Clear",
	setting:"Setting",
	logOut:"Log Out",
	calendar: "Calendar",
	external:"external",
	new:"New",
	next:"Next",
	previous:"Previous",
	announcement:"Announcement",
	formats:"Formats",
	supported:"Supported",
	sort:"Sort",
	download:"Download",
	print:"Print",
	trackStatus:"TrackStatus",
	suggested:"Suggested",
	additional:"Additional", 
	comments:"Comments",
	attachments:"Attachments",
	textRquiredMsg: "Required Field",
	
	rfxSaveSuccess: "RFx Saved successfully",
	rfxDraftSaveSuccess: "Rfx Draf Saved successfully",
	rfxCancelConfirm: "",
	language:"Language",
	rfxCancelConfirm: "Your cancellation becomes effective! Do you want continue to cancel?",
	profilePageSuccessMsg: "Your Profile Saved successfully",
	profilePageErrorMsg: "May be data will get lost!",
	load:"Load",
	activities:"Activities",
	trackStatus:"TRACK STATUS",
	star: "Star",
	mailToInfo: "To Information from Label js",
	action1: "Action 1",
	action2: "Action 2",
	action3: "Action 3",
	quick: "Quick",
	wishlist: "Wishlist",
	compare: "Compare",
	list: "List",
    card:"Card",
	searchList:"Search List",
	favorite:"Favorite",
	erpOrderType:"ERP Order Type",
	workOrder:"Work Order",
	bill:"bill",
	location:"Location",
	line:"Line",
	code:"Code",
	city:"City",
	zip:"Zip",
	country:"Country",
	state:"state",
	person:"Person",
	telephone:"Telephone"
	
};

var app = angular.module('smartApp', []);
app.run(function ($rootScope) {
    $rootScope.$label = labels;
    var lowerCased = {};
    $.each(labels, function (i, v) {
        lowerCased[i] = v.toLowerCase();
    });

    $rootScope.$label_L = lowerCased;
    var upperCased = {};
    $.each(labels, function (i, v) {
        upperCased[i] = v.toUpperCase();
    });
    $rootScope.$label_U = upperCased;

    function capitalizeFirstLetter(string) {
        return string.charAt(0).toUpperCase() + string.slice(1);
    }
    var firstUpperCased = {};
    $.each(labels, function (i, v) {
        firstUpperCased[i] = capitalizeFirstLetter(v);
    });
    $rootScope.$label_FU = firstUpperCased;
});
